### ISSUE TITLE
InvalidArgumentError

### ISSUE THREAD

**Issue by provenpeng** [xxbb1234021/speech_recognition#3]
root@zp:/home/zp/Desktop/voice# python3 test.py
./train_data/wav/test/D21/D21_847.wav 中国队 首先 出场 的 是 赖 亚文 孙悦 李艳 吴 咏梅 崔 咏梅 和 何 琦 这 也是 首选 阵容
wav: 2132 label 2132
字表大小: 1787
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1305, in _run_fn
    self._extend_graph()
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'h6/Adam_1': Operationwas explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Makesure the device specification refers to a valid device.
         [[Node: h6/Adam_1 = VariableV2[_class=["loc:@h6"], container="", dtype=DT_FLOAT, shape=[512,1788], shared_name="", _device="/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 18, in <module>
    bi_rnn.build_test()
  File "/home/zp/Desktop/voice/model.py", line 336, in build_test
    self.init_session()
  File "/home/zp/Desktop/voice/model.py", line 192, in init_session
    self.sess.run(tf.global_variables_initializer())
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'h6/Adam_1': Operationwas explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Makesure the device specification refers to a valid device.
         [[Node: h6/Adam_1 = VariableV2[_class=["loc:@h6"], container="", dtype=DT_FLOAT, shape=[512,1788], shared_name="", _device="/device:GPU:0"]()]]

Caused by op 'h6/Adam_1', defined at:
  File "test.py", line 18, in <module>
    bi_rnn.build_test()
  File "/home/zp/Desktop/voice/model.py", line 335, in build_test
    self.loss()
  File "/home/zp/Desktop/voice/model.py", line 156, in loss
    self.optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(self.avg_loss)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 424, in minimize
    name=name)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 600, in apply_gradients
    self._create_slots(var_list)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/adam.py", line 132, in _create_slots
    self._zeros_slot(v, "v", self._name)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 1150, in _zeros_slot
    new_slot_variable = slot_creator.create_zeros_slot(var, op_name)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/slot_creator.py", line 181, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/slot_creator.py", line 155, in create_slot_with_initializer
    dtype)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/slot_creator.py", line 65, in _create_slot_var
    validate_shape=validate_shape)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1317, in get_variable
    constraint=constraint)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1079, in get_variable
    constraint=constraint)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 425, in get_variable
    constraint=constraint)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 786, in _get_single_variable
    use_resource=use_resource)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2220, in variable
    use_resource=use_resource)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2210, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2193, in default_variable_creator
    constraint=constraint)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 235, in __init__
    constraint=constraint)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 349, in _init_from_args
    name=name)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 137, in variable_op_v2
    shared_name=shared_name)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 1255, in variable_v2
    shared_name=shared_name, name=name)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'h6/Adam_1': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
         [[Node: h6/Adam_1 = VariableV2[_class=["loc:@h6"], container="", dtype=DT_FLOAT, shape=[512,1788], shared_name="", _device="/device:GPU:0"]()]]

**Comment by provenpeng** [comment]
root@zp:/home/zp/Desktop/voice# python3 train.py
./train_data/wav/test/D21/D21_847.wav 中国队 首先 出场 的 是 赖 亚文 孙悦 李艳 吴 咏梅 崔 咏梅 和 何 琦 这 也是 首选 阵容
wav: 2132 label 2132
字表大小: 1787
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1305, in _run_fn
    self._extend_graph()
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'h6/Adam_1': Operationwas explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Makesure the device specification refers to a valid device.
         [[Node: h6/Adam_1 = VariableV2[_class=["loc:@h6"], container="", dtype=DT_FLOAT, shape=[512,1788], shared_name="", _device="/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 19, in <module>
    bi_rnn.build_train()
  File "/home/zp/Desktop/voice/model.py", line 328, in build_train
    self.init_session()
  File "/home/zp/Desktop/voice/model.py", line 192, in init_session
    self.sess.run(tf.global_variables_initializer())
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'h6/Adam_1': Operationwas explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Makesure the device specification refers to a valid device.
         [[Node: h6/Adam_1 = VariableV2[_class=["loc:@h6"], container="", dtype=DT_FLOAT, shape=[512,1788], shared_name="", _device="/device:GPU:0"]()]]

Caused by op 'h6/Adam_1', defined at:
  File "train.py", line 19, in <module>
    bi_rnn.build_train()
  File "/home/zp/Desktop/voice/model.py", line 327, in build_train
    self.loss()
  File "/home/zp/Desktop/voice/model.py", line 156, in loss
    self.optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(self.avg_loss)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 424, in minimize
    name=name)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 600, in apply_gradients
    self._create_slots(var_list)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/adam.py", line 132, in _create_slots
    self._zeros_slot(v, "v", self._name)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 1150, in _zeros_slot
    new_slot_variable = slot_creator.create_zeros_slot(var, op_name)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/slot_creator.py", line 181, in create_zeros_slot
    colocate_with_primary=colocate_with_primary)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/slot_creator.py", line 155, in create_slot_with_initializer
    dtype)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/slot_creator.py", line 65, in _create_slot_var
    validate_shape=validate_shape)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1317, in get_variable
    constraint=constraint)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1079, in get_variable
    constraint=constraint)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 425, in get_variable
    constraint=constraint)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 786, in _get_single_variable
    use_resource=use_resource)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2220, in variable
    use_resource=use_resource)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2210, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 2193, in default_variable_creator
    constraint=constraint)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 235, in __init__
    constraint=constraint)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 349, in _init_from_args
    name=name)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 137, in variable_op_v2
    shared_name=shared_name)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 1255, in variable_v2
    shared_name=shared_name, name=name)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/root/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'h6/Adam_1': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
         [[Node: h6/Adam_1 = VariableV2[_class=["loc:@h6"], container="", dtype=DT_FLOAT, shape=[512,1788], shared_name="", _device="/device:GPU:0"]()]]

**Comment by provenpeng** [comment]
求教这个怎么解决？

**Comment by xxbb1234021** [comment]
https://blog.csdn.net/jacke121/article/details/78825001

@provenpeng

**Comment by ZeR0ll** [comment]
你好我也遇到了这个问题,但是我的电脑没有GPU,只用CPU训练请问该如何解决
