### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError:

### ISSUE THREAD

**Issue by provenpeng** [xxbb1234021/speech_recognition#6]
tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: /home/kevin/workspaces/python/speech-new-test : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
; No such process

用你的模型测试会有这种错误，求问怎么解决

**Comment by xxbb1234021** [comment]
编码问题？是在不行还是自己训练一个吧！

**Comment by provenpeng** [comment]
可是训练会有这种问题
C:\Users\zxchong\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "c:\Users\zxchong\Desktop\zp\speech_recognition-master\train.py", line 13, in <module>
    wav_files, text_labels = utils.get_wavs_lables()
  File "c:\Users\zxchong\Desktop\zp\speech_recognition-master\utils.py", line 17, in get_wavs_lables
    print(wav_files[0], text_labels[0])
IndexError: list index out of range

[FILE_DATA]
wav_path=F:\xunlei\data\data_thchs30\train
label_file=C:\Users\zxchong\Desktop\zp\speech_recognition-master\train_data\voice/test.word.txt
savedir=C:\Users\zxchong\Desktop\zp\speech_recognition-master\train_data\voice\model
savefile=speech.cpkt
tensorboardfile=C:\Users\zxchong\Desktop\zp\speech_recognition-master\train_data\voice
不知道为什么

**Comment by xxbb1234021** [comment]
wav_files, text_labels = utils.get_wavs_lables()
这行代码你debug进去看看，返回的是什么？

**Comment by provenpeng** [comment]
可能是label_file没弄对，训练时 label_file用哪个？（我训练用的语音是data_thchs30\train），但是您发的data_thchs30的网站好像没有对应的label_file

**Comment by provenpeng** [comment]
我用你上传的test语音训练可以运行，但是总是重复那几句

**Comment by xxbb1234021** [comment]
就是在下载训练数据网页的最下面有个百度网盘
https://pan.baidu.com/s/1hqKwE00#list/path=%2F

**Comment by sunshinepython** [comment]
我下载了清华的那个数据，训练语音用wav_path =/data_thchs30/train， 但是label_file该怎么设置呢，清华的这个train文件中是有后缀为.wav.trn的文件，请问大佬训练的时候是怎么使用清华的这个数据的 @xxbb1234021

**Comment by chenyuqing** [comment]
遇到同样的问题，已解决，修改checkpoint文件里面的路径为自己的路径，而不是kevin本身的路径。
kevin的路径是：
model_checkpoint_path: "/home/kevin/workspaces/python/speech-new-test/speech.cpkt-101"
all_model_checkpoint_paths: "/home/kevin/workspaces/python/speech-new-test/speech.cpkt-101"

修改为自己的路径：(我的是)
model_checkpoint_path: "/home/honghaier1688/workspaces/speech_recognition-master/opt/tf/speechtest/speech.cpkt-101"
all_model_checkpoint_paths: "/home/honghaier1688/workspaces/speech_recognition-master/opt/tf/speechtest/speech.cpkt-101"

然后就可以加载模型跑了。

**Comment by chenyuqing** [comment]
@provenpeng @xxbb1234021

**Comment by chenyuqing** [comment]
@provenpeng @xxbb1234021 
遇到同样的问题，已解决，修改checkpoint文件里面的路径为自己的路径，而不是kevin本身的路径。
kevin的路径是：
model_checkpoint_path: "/home/kevin/workspaces/python/speech-new-test/speech.cpkt-101"
all_model_checkpoint_paths: "/home/kevin/workspaces/python/speech-new-test/speech.cpkt-101"

修改为自己的路径：(我的是)
model_checkpoint_path: "/home/tim/workspaces/speech_recognition-master/opt/tf/speechtest/speech.cpkt-101"
all_model_checkpoint_paths: "/home/tim/workspaces/speech_recognition-master/opt/tf/speechtest/speech.cpkt-101"

然后就可以加载模型跑了。

**Comment by chenyuqing** [comment]
出来的效果是这样的：
![screenshot from 2018-06-29 11-41-21](https://user-images.githubusercontent.com/8035422/42072092-63c352c6-7b91-11e8-9f96-d97fd9e5b512.png)

**Comment by chenyuqing** [comment]
测试结果：
![screenshot from 2018-06-29 11-49-38](https://user-images.githubusercontent.com/8035422/42072333-87a6f4bc-7b92-11e8-805e-f55e391b2d5f.png)

**Comment by aikekeaishenghuo** [comment]
> 可是训练会有这种问题
> C:\Users\zxchong\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
> from ._conv import register_converters as _register_converters
> Traceback (most recent call last):
> File "c:\Users\zxchong\Desktop\zp\speech_recognition-master\train.py", line 13, in 
> wav_files, text_labels = utils.get_wavs_lables()
> File "c:\Users\zxchong\Desktop\zp\speech_recognition-master\utils.py", line 17, in get_wavs_lables
> print(wav_files[0], text_labels[0])
> IndexError: list index out of range
> 
> [FILE_DATA]
> wav_path=F:\xunlei\data\data_thchs30\train
> label_file=C:\Users\zxchong\Desktop\zp\speech_recognition-master\train_data\voice/test.word.txt
> savedir=C:\Users\zxchong\Desktop\zp\speech_recognition-master\train_data\voice\model
> savefile=speech.cpkt
> tensorboardfile=C:\Users\zxchong\Desktop\zp\speech_recognition-master\train_data\voice
> 不知道为什么

**Comment by Titook** [comment]
> @provenpeng @xxbb1234021 遇到同样的问题，已解决，修改checkpoint文件里面的路径为自己的路径，而不是kevin本身的路径。 kevin的路径是： model_checkpoint_path: "/home/kevin/workspaces/python/speech-new-test/speech.cpkt-101" all_model_checkpoint_paths: "/home/kevin/workspaces/python/speech-new-test/speech.cpkt-101"
> 
> 修改为自己的路径：(我的是) model_checkpoint_path: "/home/tim/workspaces/speech_recognition-master/opt/tf/speechtest/speech.cpkt-101" all_model_checkpoint_paths: "/home/tim/workspaces/speech_recognition-master/opt/tf/speechtest/speech.cpkt-101"
> 
> 然后就可以加载模型跑了。

你好，我想问一下checkpoint文件里面怎么知道自己的路径呢
